### ISSUE TITLE
pre-project management

### ISSUE THREAD

**Issue by dittm** [dittm/DubLitOr#1]
- [x] Situationsanalyse
- [x] Definition und Beschreibung der Working Packages
- [x] Zuordnung der Work Packages zu Personen = Assignees zu Issues hinzufügen
- [x] Zuweisung der (Sub-)Tasks und Milestones = Issues anlegen, Labels vergeben (v.a. Aufwandsabschätzung [high, medium, low] und WP) und Milestones angeben
- [x] Visuelle Darstellung des Projektstrukturplans = Baumdiagramm hochladen und im Wiki bei Projektstrukturplan verlinken
- [x] Feststellen kritischer Tasks und möglicher Alternativen
- [x] Gantt

**Comment by johofe** [comment]
Arbeite an der Definition und Beschreibung der Working Packages.
